### ISSUE TITLE
iOS touch events question !

### ISSUE THREAD

**Issue by dorald** [armadillu/ofxSceneManager#1]
hi.
How to get touch events inside scenes ?

**Comment by armadillu** [comment]
hey have a look at the updated example in the last commit. Basically you only need to forward them from testApp to the sceneManager... Then just declare the event method in all your scenes, and you will get them called by the sceneManager.

**Comment by dorald** [comment]
Nice... :+1:   for touch events call sceneManager->touchDown(touch);

Thank you.
